### ISSUE TITLE
关于GFlops统计和params统计

### ISSUE THREAD

**Issue by Mr-Bigworth** [yangli18/VLTVG#12]
您好，请问论文中这两个指标的统计，在project中有相关的统计脚本不，谢谢！

**Comment by yangli18** [comment]
@Mr-Bigworth 
这个 project 里暂时没有相关统计脚本，#params 可以直接对模型权重统计参数个数，GFLops 统计可以参考下面链接：
https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c#file-flop_count-py
https://github.com/facebookresearch/fvcore/blob/51092b5515cbb493f73de079743dd6b11cc4bbf1/fvcore/nn/flop_count.py

**Comment by Mr-Bigworth** [comment]
好的，谢谢！
