### ISSUE TITLE
The dataset of ReferItGame and Flickr30k is unavailable.

### ISSUE THREAD

**Issue by WujiangXu** [yangli18/VLTVG#2]
Thank u for u solid work.  I follow your repository and meet some problems. 

On one hand, the link of the dataset ReferItGame in the download_data.sh script is unavailable. I can't download the file from this link.
On the other hand, it is no provided way to download the dataset Flickr30k.

Can u give some suggestions?

**Comment by WujiangXu** [comment]
By the way, are there some interpretations for the config py file?

**Comment by yangli18** [comment]
@WujiangXu
Hi, the download link for ReferItGame seems to be broken. As an alternative, you can download all the images from the [ImageCLEF](https://www.imageclef.org/SIAPRdata), from which the ReferItGame is collected. Or you can try using the subset of images from [here](https://bvisionweb1.cs.unc.edu/licheng/referit/data/images/saiapr_tc-12.zip) (provided by https://github.com/lichengunc/refer#prepare-images).  

The images of Flickr30k need to be downloaded from its [homepage](http://shannon.cs.illinois.edu/DenotationGraph/).  Please note that the images should be prepared according to the folder structure mentioned in [get_started.md](https://github.com/yangli18/VLTVG/blob/master/docs/get_started.md).

**Comment by yangli18** [comment]
@WujiangXu 
The configuration files contain the arguments that we want to pass to the training/testing script. For example, "epochs=90" in the configuration file means training for 90 epochs, which is equivalent to specifying "--epoch 90" in the command line.
