### ISSUE TITLE
about verification score

### ISSUE THREAD

**Issue by Leavelk** [yangli18/VLTVG#3]
Hello, I have some doubts about the calculation of the verification score in formula 1, can you tell me why the verification score is calculated like this?
Can you provide the code for the verification score visualization? 
thank you very much!

**Comment by yangli18** [comment]
@PengLongkun 
Hi, you could refer to [the paper](https://arxiv.org/abs/2205.00272) for a detailed explanation. In a nutshell, formula 1 projects the visual and textual features into the same semantic space, and calculates the verification scores to find the correlations between them. We use the verification scores to highlight the semantically related objects/regions for grounding. 

We may add a demo script for score visualization when we have time later, but we don't have much time recently. So we suggest you can implement this yourself.

**Comment by Leavelk** [comment]
Thanks a lot, I'll have a try.
