### ISSUE TITLE
Visualize the attention map for a point

### ISSUE THREAD

**Issue by fawnliu** [yangli18/VLTVG#4]
Thank you for your great work.  
Could you tell me how to visualize the attention map for a point in Fig.4, or share its code?

<img width="500" alt="0" src="https://user-images.githubusercontent.com/17973682/172041563-3161bb46-0bbd-45b0-9e5c-12895df6723f.png">

**Comment by yangli18** [comment]
@scarleatt 
Hi! During inference, the context encoder calculates a language-guided self-attention map for the input image, which is of the shape HWxHW. You can first cache the entire self-attention map and then obtain the attention map for any point from this self-attention map by its location. Reshape the obtained attention map to HxW and you can visualize it.

**Comment by fawnliu** [comment]
Thank you very much for the quick reply, I'll have a try.
