### ISSUE TITLE
Split of Flickr30K dataset

### ISSUE THREAD

**Issue by tiger990111** [yangli18/VLTVG#7]
Dear, I find that the split file flickr_train.pth has 427193 datas, which is supposed to has 29,783 training datas. So is it a mistake in the data.tar? or how can we get the correct split files. Thanks!

**Comment by yangli18** [comment]
@tiger990111 Hi. The training set's 427,193 image-text pairs contain many duplicate images, which means that one image could have more than one associated text. 29,779 training images were actually used. You can recheck it.

**Comment by tiger990111** [comment]
Understood, so there are 29,779 images in training set, but the size of traing set is  427,193.

**Comment by yangli18** [comment]
Yes.
