### ISSUE TITLE
Hello, the download link of the "ReferitGame" dataset is no longer available. Could you please send me a file through other methods? Thank you very much!

### ISSUE THREAD

**Issue by Rose-bud** [yangli18/VLTVG#8]
Hello, thanks for your work. I have a problem that the download link of the "ReferitGame" dataset is no longer available. Could you please send me a file through other methods? Thank you very much!

**Comment by yangli18** [comment]
@Rose-bud 
Hi, I have updated the alternative download links for the ReferitGame dataset. Please check it out.
