### ISSUE TITLE
How to visualize the attention map

### ISSUE THREAD

**Issue by tiger990111** [yangli18/VLTVG#9]
Dear, thanks for your great job. I am now wanting to reproduce your job. Can you tell me how you visualize your attention map w.r.t. those picture in your paper?

**Comment by yangli18** [comment]
Hi, we use Matplotlib for visualizing the attention map. You can refer to this [website](https://matplotlib.org/stable/gallery/images_contours_and_fields/layer_images.html#sphx-glr-gallery-images-contours-and-fields-layer-images-py).
